spring:
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.23.65:3306/student_dynamics_test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: org_api
    password: dinglicom
    hikari:
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 10000
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: MYSQL


logging.level.com.aizhixin.cloud: DEBUG

ftp:
  host: 114.67.48.139
  port: 21
  username: aizhixin
  password: NAVHWK6ADMVKDKW3a.
  # 本地目录
  remote-dir: /aizhixin
  local-dir: /Users/hsh/Downloads/data
  command-filename: synccommand.txt

log-dir: /Users/hsh/Downloads/data/logs

db:
  config.filename: syncconfig.zip
  config.dir: /Users/hsh/Downloads/data/tt
  out.dir: /Users/hsh/Downloads/data/tout
  batch.size: 1000

sys:
  version: v0.0.1