spring:
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@202.193.95.1:1521:glutdb1
    username: gxzjk
    password: C5vvgEkf97fLFwvofijzq8waC9
    hikari:
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 10000

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: ORACLE

logging.level.com.aizhixin.cloud: DEBUG

ftp:
  host: 114.67.48.139
  port: 21
  username: aizhixin
  password: NAVHWK6ADMVKDKW3a.
  # 本地目录
  remote-dir: /aizhixin
  local-dir: D://data
  command-filename: synccommand.txt

log-dir: D://data/logs

db:
  config.filename: syncconfig.zip
  config.dir: D://data/tt
  out.dir: D://data/tout
  batch.size: 1000

sys:
  version: v0.0.1